# Generated by Django 5.0.7 on 2024-11-07 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratKeluarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_surat', models.DateField(blank=True, null=True)),
                ('hal', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('kode_balai_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.balaimodel')),
                ('suku_masalah_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.sukumasalahmodel')),
            ],
            options={
                'verbose_name': 'SuratKeluarModel',
                'verbose_name_plural': 'SuratKeluarModels',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
