# Generated by Django 5.0.7 on 2024-11-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suratkeluarmodel',
            table='surat_keluar',
        ),
    ]
