# Generated by Django 5.0.7 on 2024-11-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0003_alter_suratkeluarmodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suratkeluarmodel',
            old_name='kode_balai_id',
            new_name='kode_balai',
        ),
        migrations.RenameField(
            model_name='suratkeluarmodel',
            old_name='suku_masalah_id',
            new_name='suku_masalah',
        ),
    ]
