# Generated by Django 5.0.7 on 2024-11-08 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_tandatanganmodel_kode'),
        ('surat', '0004_rename_kode_balai_id_suratkeluarmodel_kode_balai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratkeluarmodel',
            name='ttd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.tandatanganmodel'),
        ),
        migrations.AlterField(
            model_name='suratkeluarmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='surat_keluar/'),
        ),
    ]
