# Generated by Django 5.0.7 on 2024-11-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0005_suratkeluarmodel_ttd_alter_suratkeluarmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratkeluarmodel',
            name='no_urut',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
