# Generated by Django 5.0.7 on 2024-08-13 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_balai', models.CharField(blank=True, max_length=32)),
                ('nama_balai', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Kode Balai',
            },
        ),
        migrations.CreateModel(
            name='KlasifikasiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasifikasi_arsip', models.CharField(blank=True, choices=[(None, '- Pilih - '), ('fasilitasif', 'Fasilitatif'), ('substantif', 'Substantif')], max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Klasifikasi Arsip',
            },
        ),
        migrations.CreateModel(
            name='MasalahPokokModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=6)),
                ('masalah_pokok', models.CharField(blank=True, max_length=128)),
                ('klasifikasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.klasifikasimodel', verbose_name='Klasifikasi Arsip')),
            ],
            options={
                'verbose_name_plural': 'Masalah Pokok',
            },
        ),
        migrations.CreateModel(
            name='BagianMasalahModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=6)),
                ('bagian_masalah', models.CharField(blank=True, max_length=128)),
                ('masalahpokok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.masalahpokokmodel', verbose_name='Masalah Pokok')),
            ],
            options={
                'verbose_name_plural': 'Bagian Masalah',
            },
        ),
        migrations.CreateModel(
            name='SukuMasalahModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=6)),
                ('suku_masalah', models.CharField(blank=True, max_length=128)),
                ('bagianmasalah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.bagianmasalahmodel', verbose_name='Bagian Masalah')),
            ],
            options={
                'verbose_name_plural': 'Suku Masalah',
            },
        ),
    ]
