# Generated by Django 5.0.7 on 2024-11-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_tandatanganmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandatanganmodel',
            name='kode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
