# Generated by Django 5.0.7 on 2024-11-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuratMasukModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(blank=True, max_length=150, null=True)),
                ('tgl_surat', models.DateField(blank=True, null=True)),
                ('hal', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='surat_masuk/')),
            ],
            options={
                'verbose_name': 'SuratMasukModel',
                'verbose_name_plural': 'SuratMasukModels',
                'db_table': 'tb_surat_masuk',
                'managed': True,
            },
        ),
    ]
